openapi: 3.0.0
info:
  title: fnfhnf
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /fnfs:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-fnfs
components:
  schemas:
    fnf-model:
      title: fnf-model
      type: object
      properties:
        id:
          type: string
