openapi: 3.0.0
info:
  title: GHapi
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /things:
    get:
      summary: Your GET endpoint
      tags:
        - ggg
      responses: {}
      operationId: get-things-
    parameters: []
components:
  schemas:
    modelor:
      title: modelor
      type: object
      properties:
        id:
          type: string
