openapi: 3.0.0
info:
  title: Some sort of API
  version: '1.0'
  description: 'Description here  '
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - type: string
        name: userId
        in: path
        required: true
    get:
      summary: Your GET endpoint
      tags:
        - nother
      responses: {}
      operationId: get-users-userId-
components:
  schemas: {}
